env: prod
http:
  host: 0.0.0.0
  port: 8000
security:
  jwt:
    key: QQYnRFerJTSEcrfB89fw8prOaObmrch8
data:
  db:
    user:
      driver: mysql
      # dsn: storage/webstack-go.db?_busy_timeout=5000
      dsn: webstackgoai:webstackgoai@tcp(127.0.0.1:13306)/webstackgoai?charset=utf8mb4&parseTime=True&loc=Local

log:
  log_level: info
  encoding: console           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true

template:
  index_theme: "index_ai" # the name under templates/
